server:
  port: 8761

eureka:
  instance:
    hostname: hongto-w10.corp.oocl.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: eurka-server